### ISSUE TITLE
Use of RESTful verbs (maybe every request shouldn't be a POST?)

### ISSUE THREAD

**Issue by twanlass** [bufferapp/authentication-service#1]
Heya Harrison, 
Just a quick thought here – there may be another reason to have these endpoints all be `POST` requests (conformity with other services, legacy systems, et el). 

- `POST` – `api/create`
- `GET` – `api/get`
- `POST` - `api/productlinks/create`
- `DELETE` – `api/productlinks/remove`
- `PUT/PATCH` – `api/password/update`
- `POST` – `api/password/reset/start`
- `POST` – `api/password/reset/complete`
- `GET / POST` – `api/verify`(don't think this endpoint creates anything to start, right?)

**Comment by hharnisc** [comment]
This one is tricky, these endpoints are _kind of_ restful in structure. Things like `api/password/reset/*` and `api/verify` don't quite fit into the restful API for instance. I think this API is closer to a RPC structure. Going fully restful feels overkill for this service since you'd have to remember (and implement) each request type. Keeping everything POST and json data allows us to use the same methods of parsing and error handling for the endpoints on the server. It will also be the same story for the client. 

Would love to hear if Reply is using tools or libraries that expect restful endpoints -- would be happy to change it over in that case!
