### ISSUE TITLE
Yarn vs. npm

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/authentication-service#12]
In the spirit of standardization, should we use yarn or npm? Do you have feelings on this?

https://github.com/bufferapp/authentication-service/blob/b8869b403ce6dcde7ecc3294eca387fc4f784111/Dockerfile#L8-L11

As a side note, I think we should carry your `ADD package-lock.json` to all other repos running npm or yarn that support it 😄

**Comment by hharnisc** [comment]
6 months ago I would have said Yarn was the way to go for everything, since it was an instant speed boost. Since npm addressed the speed issues (and a bunch of security stuff!) I'd opt to defaulting towards npm unless there's a good reason to use Yarn. Less risk in using npm since they're so closely tied to node and they solve most of the big issues.

The frontend apps we've got that use Lerna are great examples of when Yarn is super helpful -- they use [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) under the hood (npm might get a similar concept soon) and make it way easier to work with local dependent packages.

And yes! Let's bring the package-lock.json file in the other applications! Install time will go down and we might even want to look at using `npm ci` for travis installs.
