### ISSUE TITLE
Encrypting or hashing user emails

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/authentication-service#17]
With GDPR as a hot topic, I am wondering if we could hash or encrypt a user's email. What are your thoughts @hharnisc?

**Comment by hharnisc** [comment]
Been thinking through this one for a bit, initially I thought it might be good to hash the email -- since that would allow us to still index the field. But I think we might want to use the email address elsewhere (for marketing purposes, billing, etc.) So I think we need to keep it plain text. This means we'll have to provide a way for someone to delete it. Going to close this one for now, but feel free to re-open it if the requirements change.

**Comment by djfarrelly** [comment]
@hharnisc sounds good. I think we could opt to encrypt this in the future if we so choose as well!
