### ISSUE TITLE
How are productLinks / productTokens meant to be used?

### ISSUE THREAD

**Issue by twanlass** [bufferapp/authentication-service#6]
Just for some clarification here – are productTokens meant to be unique per user? Per product? Are these seen as something like a client Id (but instead of a client, for product)?

**Comment by hharnisc** [comment]
I've been thinking about productTokens being `per user`. They're random state generated by the `authorization service` that can be stored by external products (Reply, Analyze, etc.) as a way to prove that the external product is who they say they are and that the user has in fact created a product link for the given product. So these should be treated more like secrets -- since they're required with the `email` and `password` to get a :+1: they are who they say they are.

The authorization service returns the `foreignKey` that was passed into the [api/productlinks/create](https://github.com/bufferapp/authentication-service#apiproductlinkscreate) endpoint. Which can be used by Reply to make sure the correct user has been authenticated.
